### Listar usuarios
GET http://localhost:3000/grupo-a/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5N2M2MTIyLTI5YmQtNGI1MS1hY2U5LWZlMjE1NzFmNjEyNiIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5MzM2NTEwLCJleHAiOjE2MzkzMzY1MjV9.RV4zFnWwiTyDItlVe3sb9VfQ5D7C6SPdPIpPbEJmAjc

### Crear usuario
POST http://localhost:3000/grupo-a/usuarios
Content-Type: application/json

{
    "email": "felipe.perezc@cutem.cl",
    "password": "patata2021"
}

### Login
POST http://localhost:3000/grupo-a/login
Content-Type: application/json

{
    "email": "felipe.perezc@utem.cl",
    "password": "patata2021"
}

### Refrescar token
GET http://localhost:3000/grupo-a/login/refresh

### Eliminar token
DELETE http://localhost:3000/grupo-a/login/refresh

### Listar estaciones
GET http://localhost:3000/grupo-a/stations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5N2M2MTIyLTI5YmQtNGI1MS1hY2U5LWZlMjE1NzFmNjEyNiIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5MzQzMjMzLCJleHAiOjE2MzkzNDMyNDh9.udpLZqUJdp5K5OWMCRwij-irkJZHl-9ZM1q5i4OU9EE