### Listar usuarios
GET http://localhost:3000/grupo-a/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzRhMzNjLWUwZjYtNDIzZi04NjViLTgxMDRkY2FmNTU2YSIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5MzcyNjg5LCJleHAiOjE2MzkzNzM1ODl9.9kR2XN9J-C40TsNTdnfAllTH82DiDnoXbyAAORSHWSo

### Crear usuario
POST http://localhost:3000/grupo-a/usuarios
Content-Type: application/json
{
    "email": "felipe.perezc@cutem.cl",
    "password": "patata2021"
}

### Login
POST http://localhost:3000/grupo-a/login
Content-Type: application/json
{
    "email": "felipe.perezc@utem.cl",
    "password": "patata2021"
}

### Refrescar token
GET http://localhost:3000/grupo-a/login/refresh

### Eliminar token
DELETE http://localhost:3000/grupo-a/login/refresh

### Listar estaciones
GET http://localhost:3000/grupo-a/stations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyYjBmMjA2LWEzODgtNGViOS1iYTE0LWQ3YjM4MDhlMTk4NCIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NDM0OTY1LCJleHAiOjE2Mzk0MzU4NjV9.TzDkUZ71uP2gOVPT-_UH97NkEEBzNG_Lu30OLAp3d_g

### Listar informacion de a partir de codigo de estacion
GET http://localhost:3000/grupo-a/200006/stations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyYjBmMjA2LWEzODgtNGViOS1iYTE0LWQ3YjM4MDhlMTk4NCIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NDMyMTQwLCJleHAiOjE2Mzk0MzMwNDB9.bFNMKdDyjhKBGjgL4WGkr96SsJxhQPj8bkH-kgqYpkM

### Listar indiciadores (temp.max = 1 temp.min = 2 precipitacion = 3) y su valer en un rango de fecha
POST http://localhost:3000/grupo-a/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyYjBmMjA2LWEzODgtNGViOS1iYTE0LWQ3YjM4MDhlMTk4NCIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NDM5NDc1LCJleHAiOjE2Mzk0NDAzNzV9.cUkqxVrROON_sN_KW_Mu4-uojzg6kL9vkRAmOZLufE0
Content-Type: application/json
{
    "indicador": "1",
    "desde": "2021-12-13",
    "hasta": "2021-12-15"
}

### Listar clima para hoy por ubicacion
GET http://localhost:3000/grupo-a/3/-20/-70/estimate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyYjBmMjA2LWEzODgtNGViOS1iYTE0LWQ3YjM4MDhlMTk4NCIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NDQ1MjI1LCJleHAiOjE2Mzk0NDg4MjV9.nURYKFhlkkqerWaZOIQe5i4R9esPCSMqhbhxKN264SU