### Listar usuarios
GET http://sugoidesuka.freeddns.us:3000/grupo-a/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3MWUzN2UxLTgxMmYtNDE4NS04YTNjLWNjZTBiYTZjNDkwYiIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NzIxNDIzLCJleHAiOjE2Mzk3MjUwMjN9.3yRYijYlxL8_x4evrifeGZ65cEz_KWLd3aEwDbl7jj4

### Crear usuario
POST http://sugoidesuka.freeddns.us:3000/grupo-a/usuarios
Content-Type: application/json

{
    "email": "felipe.perezc@cutem.cl",
    "password": "patata2021"
}

### Login
POST http://sugoidesuka.freeddns.us:3000/grupo-a/login
Content-Type: application/json

{
    "email": "felipe.perezc@utem.cl",
    "password": "232126788"
}

### Refrescar token
GET http://sugoidesuka.freeddns.us:3000/grupo-a/login/refresh

### Eliminar token
DELETE http://sugoidesuka.freeddns.us:3000/grupo-a/login/refresh

### Listar estaciones
GET http://sugoidesuka.freeddns.us:3000/grupo-a/stations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3MWUzN2UxLTgxMmYtNDE4NS04YTNjLWNjZTBiYTZjNDkwYiIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NzU5MTY1LCJleHAiOjE2Mzk3NjI3NjV9.RQIeScZ6SCfwNYjuM5qPs1wCaIJ_9R5bVAc3FPCG96w

### Listar informacion de a partir de codigo de estacion
GET http://sugoidesuka.freeddns.us:3000/grupo-a/200006/stations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyYjBmMjA2LWEzODgtNGViOS1iYTE0LWQ3YjM4MDhlMTk4NCIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NDMyMTQwLCJleHAiOjE2Mzk0MzMwNDB9.bFNMKdDyjhKBGjgL4WGkr96SsJxhQPj8bkH-kgqYpkM

### Listar indiciadores (temp.max = 1 temp.min = 2 precipitacion = 3) y su valer en un rango de fecha
POST http://sugoidesuka.freeddns.us:3000/grupo-a/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3MWUzN2UxLTgxMmYtNDE4NS04YTNjLWNjZTBiYTZjNDkwYiIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NjkyNDI3LCJleHAiOjE2Mzk2OTYwMjd9.PZ5WQFHsdDUUAkyx-KVANWkWLTByi13fdTq2SI0rOBs
Content-Type: application/json

{
    "indicador": "1",
    "desde": "2021-12-13",
    "hasta": "2021-12-15"
}

### Listar clima para hoy por ubicacion
GET http://sugoidesuka.freeddns.us:3000/grupo-a/-20/-70/estimate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3MWUzN2UxLTgxMmYtNDE4NS04YTNjLWNjZTBiYTZjNDkwYiIsImVtYWlsIjoiZmVsaXBlLnBlcmV6Y0B1dGVtLmNsIiwiaWF0IjoxNjM5NzU2ODU0LCJleHAiOjE2Mzk3NjA0NTR9.mzMLOFsY35Hh9laUhZTx7hEXVYNnSTI5LlPGlRKYhsU