-- BEGIN TRANSACTION;

 DROP TABLE IF EXISTS ESTACIONES_CLIMATOLOGICAS;
 DROP TABLE IF EXISTS TEMPERATURAS;
 DROP TABLE IF EXISTS USUARIOS;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USUARIOS (
        ID uuid DEFAULT uuid_generate_v4(),
        EMAIL TEXT NOT NULL UNIQUE,
        PASS TEXT NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID)
);

-- CREATE TABLE ESTACIONES_CLIMATOLOGICAS (
-- 		ESTACION TEXT NOT NULL,
-- 		NOMBRE char(90) NOT NULL,
-- 		LATITUD char(30) NOT NULL,
-- 		LONGITUD char(30) NOT NULL,
-- 		ALTURA_MAR float NOT NULL,
--         FECHA_CREADO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
-- 	CONSTRAINT PK_ESTACIONES_CLIMATOLOGICAS PRIMARY KEY (ESTACION)
-- );

CREATE TABLE TEMPERATURAS (
        ESTACION TEXT NOT NULL,
        FECHA_CREADO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        PRECIPITACION TEXT,
        TEMP_MIN TEXT,
        TEMP_MAX TEXT
);

INSERT INTO USUARIOS (EMAIL,PASS) VALUES ('felipe.perezc@utem.cl','patata2021')