
 DROP TABLE IF EXISTS ESTACIONES_CLIMATOLOGICAS;
 DROP TABLE IF EXISTS TEMPERATURAS;
 DROP TABLE IF EXISTS USUARIOS;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USUARIOS (
        ID uuid DEFAULT uuid_generate_v4(),
        EMAIL TEXT NOT NULL UNIQUE,
        PASS TEXT NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID)
);

CREATE TABLE TEMPERATURAS (
        ESTACION TEXT NOT NULL,
        FECHA_CREADO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        PRECIPITACION TEXT,
        TEMP_MIN TEXT,
        TEMP_MAX TEXT
);

INSERT INTO USUARIOS (EMAIL,PASS) VALUES ('felipe.perezc@utem.cl','$2b$10$yzcBQ6byb8jpVc.DGSCJKOmz8EtN/HuhLTVk.g5VIVI1d2ZLyYRm.')