-- BEGIN TRANSACTION;

 DROP TABLE IF EXISTS ESTACIONES_CLIMATOLOGICAS;
 DROP TABLE IF EXISTS TEMPERATURAS;
 DROP TABLE IF EXISTS USUARIOS;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USUARIOS (
        ID uuid DEFAULT uuid_generate_v4(),
        EMAIL char(255) NOT NULL UNIQUE,
        PASS char(255) NOT NULL,
        FECHA_CREADO timestamptz NOT NULL NOW (),
        FECHA_MOD timestamptz NOT NULL NOW (),
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID)
);

CREATE TABLE ESTACIONES_CLIMATOLOGICAS (
		COD_ESTACION int NOT NULL,
		NOMBRE char(90) NOT NULL,
		LATITUD char(30) NOT NULL,
		LONGITUD char(30) NOT NULL,
		ALTURA_MAR float NOT NULL,
                FECHA_CREADO timestamptz NOT NULL NOW (),
                FECHA_MOD timestamptz NOT NULL NOW (),
	CONSTRAINT PK_ESTACIONES_CLIMATOLOGICAS PRIMARY KEY (COD_ESTACION)
);

CREATE TABLE TEMPERATURAS (
        COD_TEMP int NOT NULL,
        COD_ESTACION int NOT NULL,
        FECHA_CREADO timestamptz NOT NULL NOW (),
        FECHA_MOD timestamptz NOT NULL NOW (),
        PRECIPITACION float,
        TEMP_MIN float,
        TEMP_MAX float,
    CONSTRAINT PK_TEMPERATURAS PRIMARY KEY (COD_TEMP),
    CONSTRAINT FK_ESTACIONES_CLIMATOLOGICAS
        FOREIGN KEY(COD_ESTACION)
            REFERENCES ESTACIONES_CLIMATOLOGICAS(COD_ESTACION)
);

INSERT INTO USUARIOS (EMAIL,PASS) VALUES ('felipe.perezc@utem.cl','patata2021')